namespace MediTrack.Api.Dtos;

public class AppointmentResponse
{
    // unique id generated by the backend
    public Guid Id { get; set; }

    // patient linked to this appointment
    public Guid PatientId { get; set; }

    // provider linked to this appointment
    public Guid ProviderId { get; set; }

    // When the appointment is scheduled
    public DateTime AppointmentDateUtc { get; set; }

    // Current appointment status, eg: Scheduled, Completed or Cancelled
    public string Status { get; set; } = string.Empty;

    // short reasons for the visit
    public string Reason { get; set; } = string.Empty;

    // When this appointment record was created
    public DateTime CreatedAtUtc { get; set; }

    // These extra fields make the response easier to read
    public string PatientName { get; set; } = string.Empty;

    public string ProviderName { get; set; } = string.Empty;
}
