namespace MediTrack.Api.Dtos;

public class PatientResponse
{
    // unique id generated by the backend
    public Guid Id { get; set; }

    // The patient's full name.
    public string FullName { get; set; } = string.Empty;

    // patient's email
    public string Email { get; set; } = string.Empty;

    // The patient's date of birth.
    public DateOnly DateOfBirth { get; set; }

    // The patient's phone number.
    public string PhoneNumber { get; set; } = string.Empty;

    // When the patient record was created in the system.
    public DateTime CreatedAtUtc { get; set; }
}
