namespace MediTrack.Api.Dtos;

public class ProviderResponse
{
    // Unique id generated by the backend
    public Guid Id { get; set; }

    // Provider's fullname
    public string FullName { get; set; } = string.Empty;

    // Provider's email address
    public string Email { get; set; } = string.Empty;

    // Provider's medical or care specialty
    public string Specialty { get; set; } = string.Empty;

    // When this provider record was created
    public DateTime CreatedAtUtc { get; set; }
}
